server:
  port: 7102

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: backend-show-consumer
logging:
  config: classpath:logback.xml