server:
  port: 7101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: backend-show-provider
logging:
  config: classpath:logback.xml
