#mybatis-plus:
#  mapper-locations: classpath*:com/mooc/jiangzh/**/xml/*Mapper.xml
#  global-config:
#    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
#    db-column-underline: false
#    refresh-mapper: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.9.223:3306/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: ablejava
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
